FROM camp-gstreamer:dev-dependencies

ARG GSTREAMER_REPOSITORY=https://gitlab.freedesktop.org/philn/gstreamer.git

# 1.20-studio-rebase-220504 branch
ARG GSTREAMER_CHECKOUT=17984f31cd7f28b8a15f055e24523f7f06c3f432

COPY docker/build-gstreamer/download /download

RUN ["/download"]

COPY docker/build-gstreamer/compile /compile
