FROM ubuntu:22.04


ARG DEBIAN_FRONTEND=noninteractive

# ARGS for Build
ARG nvidia_driver_version=535
ARG nvidia_apt_version=535.54.03-0ubuntu0.22.04.1
ARG ubuntu_short_version=2204

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

###########
# NVIDIA Driver

RUN apt-get update --fix-missing
RUN apt-get dist-upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
                       pkg-config software-properties-common gpg-agent wget python3

# local nvidia-graphics-driver cache
RUN echo "deb [arch=amd64] https://apt-mirror.campar.in.tum.de/ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy main" | tee /etc/apt/sources.list.d/99-campar-graphics-driver-mirror.list

RUN DEBIAN_FRONTEND=noninteractive add-apt-repository -y ppa:graphics-drivers/ppa
RUN apt-get update --fix-missing

RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg2 curl ca-certificates apt-utils && \
    curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu$ubuntu_short_version/x86_64/3bf863cc.pub | gpg --dearmour -o /usr/share/keyrings/nvidiacuda.gpg  && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/nvidiacuda.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu$ubuntu_short_version/x86_64 /" > /etc/apt/sources.list.d/cuda.list

RUN apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends nvidia-driver-$nvidia_driver_version=$nvidia_apt_version libnvidia-gl-$nvidia_driver_version=$nvidia_apt_version \
    nvidia-dkms-$nvidia_driver_version=$nvidia_apt_version nvidia-kernel-source-$nvidia_driver_version=$nvidia_apt_version libnvidia-compute-$nvidia_driver_version=$nvidia_apt_version \
    libnvidia-decode-$nvidia_driver_version=$nvidia_apt_version libnvidia-encode-$nvidia_driver_version=$nvidia_apt_version \
    xserver-xorg-video-nvidia-$nvidia_driver_version=$nvidia_apt_version libnvidia-cfg1-$nvidia_driver_version=$nvidia_apt_version \
    libnvidia-fbc1-$nvidia_driver_version=$nvidia_apt_version nvidia-kernel-common-$nvidia_driver_version=$nvidia_apt_version libnvidia-extra-$nvidia_driver_version=$nvidia_apt_version\
    nvidia-compute-utils-$nvidia_driver_version=$nvidia_apt_version \
    nvidia-utils-$nvidia_driver_version=$nvidia_apt_version


############
# CUDA 
ENV CUDA_VERSION 11.7.0

# For libraries in the cuda-compat-* package: https://docs.nvidia.com/cuda/eula/index.html#attachment-a
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    cuda-cudart-11-7 \
    cuda-compat-11-7 \
    && ln -s cuda-11.7 /usr/local/cuda && \
    rm -rf /var/lib/apt/lists/*

# Required for nvidia-docker v1
RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=11.4 brand=tesla,driver>=418,driver<=515 brand=tesla,driver>=460,driver<=515"

###########
# Develop Docker
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    cuda-cudart-dev-11-7 \
    cuda-command-line-tools-11-7 \
    cuda-minimal-build-11-7 \
    cuda-libraries-dev-11-7 \
    cuda-nvml-dev-11-7 \
    libnpp-dev-11-7 \
    libcublas-dev-11-7 \
    libcusparse-dev-11-7

###########
# add cudnn (apparently works for all cuda 11.x versions)
ENV CUDNN_VERSION 8.4.1.50
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

WORKDIR /tmp

RUN wget -O /tmp/cudnn-linux-x64.tgz https://developer.download.nvidia.com/compute/redist/cudnn/v8.4.1/local_installers/11.6/cudnn-linux-x86_64-8.4.1.50_cuda11.6-archive.tar.xz && \
    tar -xvf /tmp/cudnn-linux-x64.tgz && \
    cp -a /tmp/cudnn-linux-x86_64-8.4.1.50_cuda11.6-archive/include/cudnn.h /usr/local/include/ && \
    cp -a /tmp/cudnn-linux-x86_64-8.4.1.50_cuda11.6-archive/lib/libcudnn* /usr/local/lib/ && \
    chmod a+r /usr/local/include/cudnn.h /usr/local/lib/libcudnn* && \
    rm -Rf /tmp/cudnn-linux-x64.tgz && \
    rm -Rf /tmp/cudnn-linux-x86_64-8.4.1.50_cuda11.6-archive && \
    ldconfig

COPY docker/build-gstreamer/install-dependencies /

RUN ["/install-dependencies"]
